swagger: '2.0'
info:
  title: Birthday Query Microservice
  description: Microservice to query birthdays from CouchDB
  version: '1.0'
basePath: /
consumes:
  - application/json
produces:
  - application/json
paths:
  /query:
    post:
      summary: Query birthdays by date
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: Year, month, and day to query
          required: true
          schema:
            type: object
            properties:
              year:
                type: integer
              month:
                type: integer
              day:
                type: integer
      responses:
        '200':
          description: Successful query
          schema:
            type: object
        '400':
          description: Bad request
          schema:
            type: object
        '500':
          description: Internal server error
          schema:
            type: object
