version: '3.9'

services:
  flask-app:
    container_name: microservice
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "4000:4000"
    depends_on:
        - couchdb
    environment:
      - IS_PROD=True
    volumes:
      - ./cfg/config_docker.cfg:/app/config_docker.cfg

  couchdb:
    container_name: couchdb
    image: dhbw-couch:1
    ports:
      - "5984:5984"
