version: '3.9'

services:
  flask-app:
    container_name: microservice
    image: julian-microservice
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "4000:4000"
    depends_on:
        - couchdb
    environment:
      - DOCKER=True
    volumes:
      - ./cfg/config_docker.json:/app/config_docker.json

  couchdb:
    container_name: couchdb
    image: dhbw-couch:1
    ports:
      - "5984:5984"
