apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchdb
  labels:
    app: couchdb
spec:
  selector:
    matchLabels:
      app: couchdb
  template:
    metadata:
      labels:
        app: couchdb
    spec:
      containers:
      - image: rennsause/dhbw-couch:1
        imagePullPolicy: IfNotPresent
        name: couchdb
        ports:
        - containerPort: 5984
        readinessProbe:
          httpGet:
            path: /_up
            port: 5984
          initialDelaySeconds: 5
          periodSeconds: 30
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: julian-microservice
  labels:
    app: julian-microservice
spec:
  selector:
    matchLabels:
      app: julian-microservice
  template:
    metadata:
      labels:
        app: julian-microservice
    spec:
      containers:
        - image: julian-microservice
          imagePullPolicy: Never
          name: julian-microservice
          ports:
            - containerPort: 4000
          readinessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 30
          env:
            - name: "KUBERNETES"
              value: "True"
            - name: url
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: URL
            - name: database_name
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: DB
            - name: password
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: CRED1
            - name: username
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: CRED2
          volumeMounts:
            - name: config-volume
              mountPath: "/app/config_docker"
              subPath: config_docker.json
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: config
