apiVersion: v1
kind: Service
metadata:
  name: microservice
  labels:
    app: microservice
spec:
  type: ClusterIP  # Du möchtest normalerweise nicht, dass der Microservice von außerhalb des Clusters erreichbar ist
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: microservice
