swagger: '2.0'
info:
  title: Birthday Query Microservice
  description: Microservice for birthday-queries from CouchDB
  version: '1.0'
paths:
  /api/v1/get_data:
    get:
      summary: Query birthdays by date
      parameters:
        - name: month
          in: query
          required: true
          description: The month (1-12)
          schema:
            type: integer
        - name: day
          in: query
          required: true
          description: The day (1-31)
          schema:
            type: integer
      responses:
        '200':
          description: OK
        '204':
          description: No content
        '401':
          description: Invalid credentials
        '408':
          description: Timeout
        '500':
          description: Internal server error
  /health:
    get:
      summary: Health check endpoint
      responses:
        '200':
          description: Healthy
        '500':
          description: Unhealthy
